[package]
name = "custom-logger"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
log = { version = "0.4", features = ["std"] }

[lib]
name = "custom_logger"
path = "src/lib.rs"
